version: '3'
services:
  express-web:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - redis-server
  redis-server:
    image: redis/redis-stack:latest
    ports:
      - '6379:6379'
